-- 코드를 입력하세요
SELECT A.BOOK_ID, B.AUTHOR_NAME, SUBSTR(A.PUBLISHED_DATE, 1, 10) PUBLISHED_DATE
FROM BOOK A
JOIN AUTHOR B
ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE A.CATEGORY = '경제'
ORDER BY A.PUBLISHED_DATE
;
